networks:
  net_default:
    ipam:
      config:
      - {subnet: 172.18.1.0/28}
      driver: default
services:
  nginx-php-fpm:
    container_name: nginx
    extra_hosts: ['redis:172.18.1.3', 'redis_1:172.18.1.4']
    image: liux156/nginx-php7.3.5
    # build: C:/docker/web/nginx/build
    environment: 
      SKIP_CHOWN: 1
      ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: 
        remote_host=192.168.2.250
        remote_port=9001
      PHP_IDE_CONFIG: serverName=teamb
    networks:
      net_default: {ipv4_address: 172.18.1.2}
    ports: ['80:80', '89:89', '9000:9000','443:443']
    restart: always
    volumes: ['C:/phpStudy/PHPTutorial/WWW:/var/www/html/:rw', './nginx/etc/nginx/:/etc/nginx/:ro','./nginx/usr/local/etc/php:/usr/local/etc/php:rw']
  nginx-php7.1.12:
    container_name: nginx-php7.1.12
    extra_hosts: ['redis:172.18.1.3', 'redis_1:172.18.1.4']
    image: liux156/nginx-php7.1.12
    # build: C:/docker/web/nginx/build
    environment: 
      SKIP_CHOWN: 1
      ERRORS: 1
    networks:
      net_default: {ipv4_address: 172.18.1.6}
    ports: ['81:80','8443:443']
    restart: always
    volumes: ['C:/phpStudy/PHPTutorial/WWW:/var/www/html/:rw', './nginx-php7.1.12/etc/nginx/:/etc/nginx/:ro','./nginx-php7.1.12/usr/local/etc/php:/usr/local/etc/php:rw']
  redis:
    command: redis-server /etc/redis/redis.conf
    container_name: redis
    image: redis
    networks:
      net_default: {ipv4_address: 172.18.1.3}
    ports: ['6379:6379']
    restart: always
    volumes: ['./redis/redis.conf:/etc/redis/redis.conf']
  redis_1:
    command: redis-server /etc/redis/redis.conf
    container_name: redis_1
    image: redis
    networks:
      net_default: {ipv4_address: 172.18.1.4}
    ports: ['6380:6380']
    restart: always
    volumes: ['./redis_1/redis.conf:/etc/redis/redis.conf']
  rabittmq:
    container_name: rabittmq
    image: rabbitmq:3.7.14-management-alpine
    networks:
      net_default: {ipv4_address: 172.18.1.5}
    ports: ['8080:15672']
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes: ['./mysql/data:/var/lib/mysql']
    networks:
      net_default: {ipv4_address: 172.18.1.7}
    environment:
      MYSQL_ROOT_PASSWORD: root
    # Port is not required to be exposed, but recommend for debug purpose
    ports:
      - "3306:3306"
  node:
    image: node
    container_name: node
    volumes: ['C:/phpStudy/PHPTutorial/WWW/grpc-master/examples:/home/node/examples/:rw']
    networks:
      net_default: {ipv4_address: 172.18.1.8}
    ports: ['10051:10051']
    command: node
    user: "node"
    working_dir: /home/node/examples/node
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      - PATH=$PATH:/home/node/.npm-global/bin
    command: "/usr/local/bin/node ./static_codegen/greeter_server.js &"
version: '2'
